trigger:
- main

pr:
- main

jobs:
- job: BuildAndDeployJob
  displayName: 'Build and Deploy Job'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    submodules: true
    lfs: false

  - task: UseNode@1
    inputs:
      version: '16.x' # Specify the Node.js version compatible with your project

  - script: npm cache clean --force
    displayName: 'Clear npm cache'

  - script: rm -rf node_modules
    displayName: 'Remove node_modules'

  - script: npm install
    displayName: 'Install dependencies'
    env:
      CI: true # Ensure non-interactive installation

  - script: npm run build
    displayName: 'Build the app'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "dist/revhire" # Built app content directory - optional
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_PEBBLE_0117D870F) # API token

  - script: cat $(Agent.TempDirectory)/npm/_logs/*.log
    displayName: 'Show npm debug log on failure'
    condition: failed()
    continueOnError: true



  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'revhire-azure-project'
      appType: 'webApp'
      WebAppName: 'revhire-appservice'
      packageForLinux: '$(System.DefaultWorkingDirectory)/dist/revhire'
      enableCustomDeployment: true
