
trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'revhire-azure-project'
    appType: 'webApp'
    WebAppName: 'revhire-appservice'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist/revhire'
    enableCustomDeployment: true
