trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trail(75833e6d-01d8-41cd-ac3a-cf5eb027f7f7)'
    appType: 'webApp'
    WebAppName: 'revhirewebapp'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deployToSlotOrASE: true
    ResourceGroupName: 'revhire-resources'
