trigger:
- main

pr:
  branches:
    include:
    - main

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '14.x'

  - script: |
      npm install -g @angular/cli
      npm install jq
      output_path=$(jq -r '.projects[].architect.build.options.outputPath' angular.json)
      echo "##vso[task.setvariable variable=output_path]$output_path"
    displayName: 'Get Angular Output Path'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: '$(output_path)'
      azure_static_web_apps_api_token: $(revhire-app3335plan (B1:1))
      repo_token: $(System.AccessToken)
      action: 'upload'

- job: ClosePullRequest
  displayName: 'Close Pull Request Job'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(revhire-app3335plan (B1:1))
      action: 'close'
