apiVersion : apps/v1
kind: Deployment
metadata:
  name: captureimg 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captureimg
  template:
    metadata:
      labels:
        app: captureimg 
    spec:
      containers:
        - name: captureimg 
          image: revhireacrchandu2001.azurecr.io/captureimg
          ports:
          - containerPort: 4200