apiVersion : apps/v1
kind: Deployment
metadata:
  name: aks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks 
    spec:
      containers:
        - name: aks 
          image: revhireacrchandu2001.azurecr.io/aks
          ports:
          - containerPort: 8082